"""
aim_data.py — AIM CSV data model
==========================================
Loads AIM CSV files generated by xrk_to_csv.py and returns the same
Session/Lap/DataPoint objects used by racebox_data.py.

Channel mapping (fuzzy, case-insensitive substring matching):
  speed    ← GPS_Speed [km/h]
  lat      ← GPS_Latitude
  lon      ← GPS_Longitude
  alt      ← GPS_Altitude
  gforce_x ← AccelerX / AccelX  (longitudinal)
  gforce_y ← AccelerY / AccelY  (lateral)
  gforce_z ← AccelerZ / AccelZ  (vertical)
  lap      ← GPS_LapBeacon / Lap
"""

from __future__ import annotations
import logging
import math
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional

from data_model import DataPoint, Session, build_laps_from_points
from exceptions import NoDataRowsError

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Channel-name patterns  (checked in order; first match wins)
# Each entry is a list of lowercase substrings to look for in the column base
# ---------------------------------------------------------------------------
_PATTERNS: dict[str, list[str]] = {
    'speed':    ['gps_speed', 'speed'],
    'lat':      ['gps_latitude', 'latitude', 'gps_lat'],
    'lon':      ['gps_longitude', 'longitude', 'gps_lon'],
    'alt':      ['gps_altitude', 'altitude', 'gps_alt'],
    # Prefer GPS-computed accelerations; fall back to raw accelerometer channels
    'gforce_x': ['gps_lonacc', 'lonacc', 'lon_acc', 'accelerometerx', 'accelerx', 'accel_x'],
    'gforce_y': ['gps_latacc', 'latacc', 'lat_acc', 'accelerometery', 'accelery', 'accel_y'],
    'gforce_z':    ['accelerometerz', 'accelerz', 'accel_z', 'vertaccel'],
    'lap':         ['gps_lapbeacon', 'lapbeacon', 'gps_lap', 'lap_beacon', 'lap'],
    'rpm':         ['rpm'],
    'exhaust_temp':['exhaust_temp', 'exhaust', 'egt', 'exh_temp'],
}


def _find_col(columns: List[str], field: str) -> Optional[str]:
    """Return the first column whose normalised name contains any pattern."""
    patterns = _PATTERNS[field]
    for pat in patterns:
        for col in columns:
            norm = col.lower().replace(' ', '_')
            if pat in norm:
                return col
    return None


def _safe(val, default: float = 0.0) -> float:
    try:
        v = float(val)
        return v if math.isfinite(v) else default
    except (ValueError, TypeError):
        return default


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def is_aim_csv(path: str) -> bool:
    """Return True if the file looks like an AIM CSV (Time (s) index)."""
    try:
        with open(path, 'r', encoding='utf-8-sig', errors='ignore') as f:
            chunk = f.read(300)
        # May have a leading '# Session-Date: …\n' comment line
        lines = chunk.splitlines()
        for line in lines[:3]:
            if line.startswith('Time (s),'):
                return True
        return False
    except Exception:
        return False


def load_csv(path: str) -> Session:
    """Load an AIM CSV (generated by xrk_to_csv.py) and return a Session."""
    try:
        import pandas as pd
    except ImportError:
        raise ImportError("pandas is required for AIM data.  pip install pandas")

    # Extract optional '# Session-Date: …' comment from the first line
    session_date_from_file: Optional[str] = None
    skip_rows = 0
    try:
        with open(path, 'r', encoding='utf-8-sig', errors='ignore') as _f:
            first_line = _f.readline().rstrip('\n')
        if first_line.startswith('# Session-Date:'):
            session_date_from_file = first_line.split(':', 1)[1].strip()
            skip_rows = 1
    except Exception:
        pass

    df = pd.read_csv(path, index_col=0, skiprows=skip_rows)
    df.index = pd.to_numeric(df.index, errors='coerce')
    df = df[df.index.notna()].sort_index()

    if df.empty:
        raise NoDataRowsError(f"No data rows in {path}")

    columns = list(df.columns)

    # Locate channels
    col = {field: _find_col(columns, field) for field in _PATTERNS}

    # Pull numeric series; interpolate NaNs so sparse GPS data is still usable.
    # Lap beacon is forward-filled only (it's a step function — no interpolation).
    def _series(name: str, step: bool = False) -> Optional[list]:
        c = col[name]
        if c is None:
            return None
        s = pd.to_numeric(df[c], errors='coerce')
        if step:
            s = s.ffill().bfill()   # carry last known lap number forward
        else:
            s = s.interpolate(method='index', limit_direction='both')
        return s.tolist()

    s_speed = _series('speed')
    s_lat   = _series('lat')
    s_lon   = _series('lon')
    s_alt   = _series('alt')
    s_gx    = _series('gforce_x')
    s_gy    = _series('gforce_y')
    s_gz    = _series('gforce_z')
    s_lap   = _series('lap', step=True)
    s_rpm   = _series('rpm')
    s_exht  = _series('exhaust_temp')

    # Speed unit conversion: AIM exports GPS Speed in m/s; we need km/h
    speed_col = col['speed']
    speed_factor = 3.6 if (speed_col and '[m/s]' in speed_col) else 1.0

    # Exhaust temp unit detection: convert °F → °C if column declares Fahrenheit
    exht_col = col['exhaust_temp']
    exht_fahrenheit = bool(exht_col and (
        '°f' in exht_col.lower() or '[f]' in exht_col.lower()
        or 'fahrenheit' in exht_col.lower()
    ))

    times = df.index.tolist()
    n     = len(times)

    # Session anchor: prefer date embedded in CSV header, fall back to file mtime
    if session_date_from_file:
        try:
            t0_dt = datetime.strptime(session_date_from_file,
                                      '%Y-%m-%dT%H:%M:%SZ').replace(tzinfo=timezone.utc)
            date_str = session_date_from_file
        except ValueError:
            session_date_from_file = None
    if not session_date_from_file:
        mtime    = os.path.getmtime(path)
        t0_dt    = datetime.fromtimestamp(mtime, tz=timezone.utc)
        date_str = t0_dt.strftime('%Y-%m-%dT%H:%M:%SZ')

    # Build DataPoints
    all_pts: List[DataPoint] = []
    for i in range(n):
        t_s = float(times[i])

        if s_lap is not None:
            raw = s_lap[i]
            lap_num = max(0, round(raw)) if (raw is not None and math.isfinite(raw)) else 0
        else:
            lap_num = 1  # no lap channel — treat whole session as one timed lap

        pt = DataPoint(
            record   = i,
            time     = t0_dt,                              # constant; elapsed is used for sync
            lat      = _safe(s_lat[i]   if s_lat   is not None else None),
            lon      = _safe(s_lon[i]   if s_lon   is not None else None),
            alt      = _safe(s_alt[i]   if s_alt   is not None else None),
            speed    = _safe(s_speed[i] if s_speed is not None else None) * speed_factor,
            gforce_x = _safe(s_gx[i]   if s_gx    is not None else None),
            gforce_y = _safe(s_gy[i]   if s_gy    is not None else None),
            gforce_z     = _safe(s_gz[i]   if s_gz    is not None else None),
            lap          = lap_num,
            gyro_x       = 0.0, gyro_y=0.0, gyro_z=0.0,
            elapsed      = t_s,
            rpm          = _safe(s_rpm[i]  if s_rpm   is not None else None),
            exhaust_temp = ((_safe(s_exht[i]) - 32.0) / 1.8
                            if exht_fahrenheit and s_exht is not None
                            else _safe(s_exht[i] if s_exht is not None else None)),
        )
        all_pts.append(pt)

    laps = build_laps_from_points(all_pts, outlap_lap_num=0)

    # Classify non-timed laps
    timed = [l for l in laps if l.lap_num > 0]
    if len(timed) >= 2:
        med = sorted(l.duration for l in timed)[len(timed) // 2]
        # Last lap: too long = cool-down/inlap; too short = session cut off mid-lap
        if timed[-1].duration > med * 1.5 or timed[-1].duration < med * 0.5:
            timed[-1].is_inlap = True
        # First timed lap: too short = recording started mid-lap
        if timed[0].duration < med * 0.5 and not timed[0].is_inlap:
            timed[0].is_outlap = True

    best_timed = [l for l in timed if not l.is_inlap and not l.is_outlap]
    best_lap_time = min((l.duration for l in best_timed), default=0.0)

    # AIM filename convention: Driver[_Number]_Track_a_Session
    # The track is the segment immediately before the fixed '_a_' separator.
    # e.g. "Toby Houston_MOSPORT_a_0669"  → "MOSPORT"
    # e.g. "Marti_7_Osona_a_1128"         → "Osona"
    stem = os.path.splitext(os.path.basename(path))[0]
    parts = stem.split('_')
    try:
        a_idx = parts.index('a')
        track = parts[a_idx - 1] if a_idx >= 2 else parts[1]
    except ValueError:
        track = parts[1] if len(parts) >= 3 else stem

    return Session(
        source        = 'AIM',
        date_utc      = date_str,
        track         = track,
        configuration = '',
        session_type  = '',
        best_lap_time = best_lap_time,
        all_points    = all_pts,
        laps          = laps,
        is_bike       = False,
        csv_path      = path,
    )
