"""
Regenerate ``canvas_export/gauge_bundle.cjs`` — concatenates editor gauge scripts
for Node (@napi-rs/canvas). Run after editing ``frontend/js/gauges/*.js``:

    python tools/bundle_canvas_gauges.py
"""
from __future__ import annotations
import os

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_GAUGES = os.path.join(_ROOT, 'frontend', 'js', 'gauges')
_OUT = os.path.join(_ROOT, 'canvas_export', 'gauge_bundle.cjs')

_ORDER = [
    'base.js',
    'numeric.js',
    'info.js',
    'scoreboard.js',
    'bar.js',
    'line.js',
    'delta.js',
    'delta_bar.js',
    'compare.js',
    'multiline.js',
    'splits.js',
    'sector_bar.js',
    'dial.js',
    'gmeter.js',
    'lean.js',
    'map.js',
    'image.js',
]

_PREAMBLE = """'use strict';
/* OpenLap — auto-generated by tools/bundle_canvas_gauges.py */
const { createCanvas, loadImage } = require('@napi-rs/canvas');
global.document = {
  createElement(tag) {
    if (tag === 'canvas') return createCanvas(1, 1);
    throw new Error('document.createElement: unsupported tag ' + tag);
  },
};
global.Image = function Image() {};
"""

_FOOTER = """
function _normalizeData(d) {
  const o = Object.assign({}, d);
  delete o._theme;
  if (!o.theme) o.theme = 'Dark';
  return o;
}

const GAUGE_STYLE_RENDERERS = {
  'Numeric':    (ctx, d, w, h) => GaugeNumeric.render(ctx, d, w, h),
  'Info':       (ctx, d, w, h) => GaugeInfo.render(ctx, d, w, h),
  'Scoreboard': (ctx, d, w, h) => GaugeScoreboard.render(ctx, d, w, h),
  'Bar':        (ctx, d, w, h) => GaugeBar.render(ctx, d, w, h),
  'Line':       (ctx, d, w, h) => GaugeLine.render(ctx, d, w, h),
  'Delta':      (ctx, d, w, h) => GaugeDelta.render(ctx, d, w, h),
  'Delta Bar':  (ctx, d, w, h) => GaugeDeltaBar.render(ctx, d, w, h),
  'Compare':    (ctx, d, w, h) => GaugeCompare.render(ctx, d, w, h),
  'Multi-Line': (ctx, d, w, h) => GaugeMultiline.render(ctx, d, w, h),
  'Splits':     (ctx, d, w, h) => GaugeSplits.render(ctx, d, w, h),
  'Sector Bar': (ctx, d, w, h) => GaugeSectorBar.render(ctx, d, w, h),
  'Dial':       (ctx, d, w, h) => GaugeDial.render(ctx, d, w, h),
  'G-Meter':    (ctx, d, w, h) => GaugeGmeter.render(ctx, d, w, h),
  'Lean':       (ctx, d, w, h) => GaugeLean.render(ctx, d, w, h),
};

function _imgPlaceholder(ctx, w, h) {
  const cell = Math.max(4, Math.round(Math.min(w, h) / 8));
  for (let y = 0; y < h; y += cell) {
    for (let x = 0; x < w; x += cell) {
      ctx.fillStyle = ((Math.floor(x / cell) + Math.floor(y / cell)) % 2 === 0) ? '#2a2a2a' : '#181818';
      ctx.fillRect(x, y, Math.min(cell, w - x), Math.min(cell, h - y));
    }
  }
  ctx.fillStyle = 'rgba(255,255,255,0.35)';
  const fs = Math.max(8, Math.round(Math.min(w, h) * 0.14));
  ctx.font = `${fs}px sans-serif`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText('IMAGE', w / 2, h / 2);
}

async function _renderImageLayer(ctx, w, h, d0) {
  const d = _normalizeData(d0);
  const p = (d.image_path || '').trim();
  if (!p) { _imgPlaceholder(ctx, w, h); return; }
  try {
    const img = await loadImage(p);
    const opacity = d.opacity != null ? Math.max(0, Math.min(1, Number(d.opacity))) : 1.0;
    const fit = d.fit || 'contain';
    const iw = img.width;
    const ih = img.height;
    let dx = 0, dy = 0, dw = w, dh = h;
    if (fit === 'contain') {
      const scale = Math.min(w / iw, h / ih);
      dw = iw * scale; dh = ih * scale;
      dx = (w - dw) / 2; dy = (h - dh) / 2;
    } else if (fit === 'cover') {
      const scale = Math.max(w / iw, h / ih);
      dw = iw * scale; dh = ih * scale;
      dx = (w - dw) / 2; dy = (h - dh) / 2;
    }
    ctx.save();
    ctx.globalAlpha = opacity;
    ctx.drawImage(img, dx, dy, dw, dh);
    ctx.restore();
  } catch (e) {
    _imgPlaceholder(ctx, w, h);
  }
}

async function renderOverlayFrame(plan) {
  const vw = plan.vw | 0;
  const vh = plan.vh | 0;
  const layers = plan.layers || [];
  const out = createCanvas(Math.max(1, vw), Math.max(1, vh));
  const g = out.getContext('2d');
  g.clearRect(0, 0, vw, vh);

  for (const L of layers) {
    const { el, style, x, y, w, h, data } = L;
    const ww = Math.max(1, w | 0);
    const hh = Math.max(1, h | 0);
    const dc = createCanvas(ww, hh);
    const dctx = dc.getContext('2d');
    const d = _normalizeData(data || {});

    if (style === 'Image') {
      await _renderImageLayer(dctx, ww, hh, d);
    } else if (el === 'map') {
      if (style === 'Zoomed') GaugeMap.renderZoomed(dctx, d, ww, hh);
      else GaugeMap.render(dctx, d, ww, hh);
    } else {
      const fn = GAUGE_STYLE_RENDERERS[style];
      if (fn) fn(dctx, d, ww, hh);
    }
    g.drawImage(dc, x | 0, y | 0);
  }
  return out;
}

module.exports = { renderOverlayFrame, createCanvas };
"""


def main() -> None:
    parts = [_PREAMBLE]
    for name in _ORDER:
        path = os.path.join(_GAUGES, name)
        with open(path, 'r', encoding='utf-8') as f:
            parts.append(f'\n/* ----- {name} ----- */\n')
            parts.append(f.read())
    parts.append(_FOOTER)
    os.makedirs(os.path.dirname(_OUT), exist_ok=True)
    with open(_OUT, 'w', encoding='utf-8') as f:
        f.write(''.join(parts))
    print('Wrote', _OUT, '(%d bytes)' % sum(len(x.encode('utf-8')) for x in parts))


if __name__ == '__main__':
    main()
